'use client'

import { useState, Suspense, lazy } from 'react'

const ImageQueriesTab = lazy(() => import('@/components/settings/ImageQueriesTab'))
const AiPromptsTab = lazy(() => import('@/components/settings/AiPromptsTab'))

type StudioTab = 'image-queries' | 'ai-prompts'

export default function ImageStudioPage() {
  const [activeTab, setActiveTab] = useState<StudioTab>('image-queries')

  const tabs: { id: StudioTab; label: string; description: string }[] = [
    { id: 'image-queries', label: 'Stock Image Queries', description: 'Refine Unsplash search terms per industry' },
    { id: 'ai-prompts', label: 'AI Image Prompts', description: 'Customise DALL-E scene hints and style prefixes' },
  ]

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">Image Studio</h1>
        <p className="text-gray-500 mt-1">Fine-tune how images are selected from Unsplash and generated by AI</p>
      </div>

      {/* Tab navigation */}
      <div className="flex gap-1 border-b border-gray-200 mb-6">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2.5 text-sm font-medium transition-colors border-b-2 -mb-px ${
              activeTab === tab.id
                ? 'border-teal-500 text-teal-700'
                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <Suspense fallback={
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-gray-200 rounded w-1/3"></div>
          <div className="h-64 bg-gray-200 rounded"></div>
        </div>
      }>
        {activeTab === 'image-queries' && <ImageQueriesTab />}
        {activeTab === 'ai-prompts' && <AiPromptsTab />}
      </Suspense>
    </div>
  )
}
