
import argparse
import yaml
import os
from openai import OpenAI

def generate_llm_content(template_path: str, user_inputs: dict, keywords: list) -> str:
    """
    Generates content using an LLM based on a YAML template, user inputs, and keywords.

    Args:
        template_path (str): Path to the YAML template file.
        user_inputs (dict): A dictionary of user-provided inputs.
        keywords (list): A list of selected keywords.

    Returns:
        str: The content generated by the LLM.
    """
    try:
        with open(template_path, 'r') as file:
            template = yaml.safe_load(file)
    except FileNotFoundError:
        return f"Error: Template file not found at {template_path}"
    except yaml.YAMLError as e:
        return f"Error parsing YAML template: {e}"

    # Extract template guidelines and example prompt
    guidelines = template.get('guidelines', "Generate content based on the following instructions:")
    example_prompt = template.get('example_prompt', "Write a compelling piece.")
    
    # Construct the prompt for the LLM
    prompt_parts = [guidelines]
    prompt_parts.append("\n---User Inputs---")
    for key, value in user_inputs.items():
        prompt_parts.append(f"{key}: {value}")
    
    if keywords:
        prompt_parts.append("\n---Keywords---")
        prompt_parts.append(", ".join(keywords))

    prompt_parts.append(f"\n---Example Prompt for LLM---")
    prompt_parts.append(example_prompt)
    
    prompt = "\n".join(prompt_parts)

    # --- LLM INVOCATION (OpenAI GPT-3.5) ---
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return "Error: OPENAI_API_KEY environment variable not set."

    client = OpenAI(api_key=api_key)

    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",  # Using GPT-3.5 Turbo
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=1024,
            temperature=0.7,
        )
        generated_content = response.choices[0].message.content
    except Exception as e:
        return f"Error during OpenAI API call: {e}"

    return generated_content

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate LLM content based on a YAML template, user inputs, and keywords.")
    parser.add_argument("--template_path", required=True, help="Path to the YAML template file.")
    parser.add_argument("--inputs", type=str, default="{}", help="JSON string of user inputs (e.g., '{\"topic\": \"AI in healthcare\"}').")
    parser.add_argument("--keywords", type=str, default="[]", help="JSON string of selected keywords (e.g., '[\"innovation\", \"future\"]').")

    args = parser.parse_args()

    import json
    try:
        user_inputs_dict = json.loads(args.inputs)
        keywords_list = json.loads(args.keywords)
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON arguments: {e}")
        exit(1)

    output_content = generate_llm_content(args.template_path, user_inputs_dict, keywords_list)
    print(output_content)
